name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.2
        with: 
              cache: npm
        
      - name: Install dependencies
        run: npm install
        
      - name: Run Linter
        run: npm run lint


  build-and-push:
    needs: quality-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: preynaga/docker_repository:tagname


  deployment:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Raspberry Pi
        run: |
          ssh -o StrictHostKeyChecking=no -p 19579 preynaga@6.tcp.eu.ngrok.io <<EOF
            docker pull preynaga/docker_repository:tagname
            docker stop my_container || true
            docker rm my_container || true
            docker run -d --name deploy -p 3000:3000 preynaga/docker_repository:tagname 
          EOF

