name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.2
        with: 
              cache: npm
        
      - name: Install dependecies
        run: npm install
        
      - name: Run Linter
        run: npm run lint
    
